/*
 * (c) Copyright 2026 CORSIKA Project, corsika-project@lists.kit.edu
 *
 * This software is distributed under the terms of the 3-clause BSD license.
 * See file LICENSE for a full version of the license.
 */

#pragma once

#include <PROPOSAL/particle/Particle.h>

#include <corsika/framework/core/ParticleProperties.hpp>
#include <corsika/accelerator/em/common/Philox.hpp>
#include <corsika/accelerator/em/common/ProcessCapabilities.hpp>
#include <corsika/accelerator/em/common/Types.hpp>
#include <corsika/modules/proposal/ProposalInteractionRecord.hpp>

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <stdexcept>
#include <utility>
#include <vector>

namespace corsika::gpu::em {

  /**
   * A draw-id range reserved for final states generated by CPU PROPOSAL after
   * the GPU has already selected type, component and v.
   *
   * GPU-native final-state kernels currently use small process-local draw
   * identifiers. Keeping CPU PROPOSAL draws above 2^32 prevents accidental
   * stream aliasing while retaining the same scheduling-independent Philox
   * addressing scheme.
   */
  inline constexpr std::uint64_t
      CpuProposalFinalStateDrawIdBase =
          std::uint64_t{1} << 32;

  inline bool isKnownProposalInteractionType(
      std::int32_t process_id) noexcept {
    using PROPOSAL::InteractionType;
    switch (static_cast<InteractionType>(process_id)) {
      case InteractionType::Particle:
      case InteractionType::Brems:
      case InteractionType::Ioniz:
      case InteractionType::Epair:
      case InteractionType::Photonuclear:
      case InteractionType::MuPair:
      case InteractionType::Hadrons:
      case InteractionType::ContinuousEnergyLoss:
      case InteractionType::WeakInt:
      case InteractionType::Compton:
      case InteractionType::Decay:
      case InteractionType::Annihilation:
      case InteractionType::Photopair:
      case InteractionType::Photoproduction:
      case InteractionType::PhotoMuPair:
      case InteractionType::Photoeffect:
        return true;
      case InteractionType::Undefined:
        return false;
    }
    return false;
  }

  /**
   * These fallback reasons are emitted after the GPU has selected the exact
   * PROPOSAL process and target component, but before it has obtained v from
   * the bounded inverse-CDF table. The CPU may therefore complete v without
   * resampling the already selected interaction.
   */
  inline bool proposalFallbackRequiresSelectedLoss(
      ProposalFallbackEvent const& event) noexcept {
    switch (event.reason) {
      case ProposalFallbackReason::InverseCdfUnavailable:
      case ProposalFallbackReason::LossEnergyOutOfRange:
      case ProposalFallbackReason::LossQuantileOutOfRange:
      case ProposalFallbackReason::NativeSelectionReplay:
        return true;
      default:
        return false;
    }
  }

  /**
   * Validate the common interaction identity and vertex state independently
   * of whether the fractional loss has already been resolved.
   */
  inline bool hasSpecifiedProposalInteractionIdentity(
      ProposalFallbackEvent const& event) noexcept {
    if (event.medium_hash == 0 ||
        event.interaction_hash == 0 ||
        !isKnownProposalInteractionType(event.process_id) ||
        !std::isfinite(event.particle.energy_GeV) ||
        !(event.particle.energy_GeV > 0.) ||
        !std::isfinite(event.particle.time_s) ||
        !std::isfinite(event.selection_uniform) ||
        event.selection_uniform < 0. ||
        event.selection_uniform >= 1.) {
      return false;
    }
    double direction_norm_squared = 0.;
    for (std::size_t axis = 0; axis < 3; ++axis) {
      if (!std::isfinite(event.particle.position_m[axis]) ||
          !std::isfinite(event.particle.direction[axis])) {
        return false;
      }
      direction_norm_squared +=
          event.particle.direction[axis] *
          event.particle.direction[axis];
    }
    return std::isfinite(direction_norm_squared) &&
           direction_norm_squared > 0.;
  }

  /**
   * True when only v is missing and the original GPU loss quantile is
   * available for exact CPU completion.
   */
  inline bool hasResolvableProposalSelectedLoss(
      ProposalFallbackEvent const& event) noexcept {
    if (!hasSpecifiedProposalInteractionIdentity(event) ||
        !proposalFallbackRequiresSelectedLoss(event)) {
      return false;
    }
    // NativeSelectionReplay invokes live PROPOSAL SampleLoss with the
    // retained selection_uniform.  Its residual conditional quantile is
    // diagnostic only and can legitimately round to exactly one at a
    // cumulative-rate boundary.  Other selected-loss completions do consume
    // loss_quantile and retain their strict half-open [0,1) contract.
    if (event.reason ==
        ProposalFallbackReason::NativeSelectionReplay) {
      return true;
    }
    return std::isfinite(event.loss_quantile) &&
           event.loss_quantile >= 0. &&
           event.loss_quantile < 1.;
  }

  /**
   * True only when a fallback contains everything needed to call
   * SecondariesCalculator::CalculateSecondaries() without selecting the
   * interaction again.
   */
  inline bool hasSpecifiedProposalFinalState(
      ProposalFallbackEvent const& event) noexcept {
    if (!hasSpecifiedProposalInteractionIdentity(event) ||
        proposalFallbackRequiresSelectedLoss(event) ||
        !std::isfinite(event.energy_fraction) ||
        event.energy_fraction < 0. ||
        event.energy_fraction > 1.) {
      return false;
    }
    return true;
  }

  /**
   * Authorize only the deliberately specified CPU final-state fallbacks.
   *
   * Data completeness alone is not authorization: InvalidFinalState and
   * transport/table failures can also retain a syntactically complete
   * interaction record.  Retrying those through PROPOSAL would hide a device
   * defect.  CPU-only physics processes and the explicitly bounded Epair
   * rejection envelope are the two production cases in which v is already
   * selected and CPU PROPOSAL is allowed to generate only the final state.
   */
  inline bool permitsSpecifiedProposalCpuFinalState(
      ProposalFallbackEvent const& event) noexcept {
    if (!hasSpecifiedProposalFinalState(event)) {
      return false;
    }
    if (event.reason == ProposalFallbackReason::CpuOnlyProcess) {
      return gpuProcessCapability(
                 event.particle.pid, event.process_id) ==
             GpuProcessCapability::CpuOnlyFinalState;
    }
    if (event.reason ==
        ProposalFallbackReason::EpairRejectionEnvelopeExceeded) {
      return event.process_id == ElectronPairProcessId &&
             (event.particle.pid ==
                  static_cast<std::int32_t>(EmPid::Electron) ||
              event.particle.pid ==
                  static_cast<std::int32_t>(EmPid::Positron));
    }
    return false;
  }

  namespace proposal_fallback_detail {

    inline proposal::ProposalInteractionRecord
    makeRecordFromIdentity(
        ProposalFallbackEvent const& event,
        std::uint64_t random_seed,
        std::uint64_t shower_id) {
      if (!hasSpecifiedProposalInteractionIdentity(event)) {
        throw std::invalid_argument(
            "GPU fallback does not contain a specified PROPOSAL interaction identity");
      }
      if (event.medium_hash >
              std::numeric_limits<std::size_t>::max() ||
          event.interaction_hash >
              std::numeric_limits<std::size_t>::max() ||
          event.component_hash >
              std::numeric_limits<std::size_t>::max()) {
        throw std::overflow_error(
            "GPU fallback PROPOSAL hash does not fit size_t");
      }

      auto const projectile_id = convert_from_PDG(
          static_cast<PDGCode>(event.particle.pid));
      if (projectile_id == Code::Unknown) {
        throw std::invalid_argument(
            "GPU fallback contains an unknown projectile PDG code");
      }

      proposal::ProposalInteractionContext context{};
      context.projectile_id = projectile_id;
      context.medium_hash =
          static_cast<std::size_t>(event.medium_hash);
      context.projectile_energy_MeV =
          event.particle.energy_GeV * 1000.;
      for (std::size_t axis = 0; axis < 3; ++axis) {
        context.position_cm[axis] =
            event.particle.position_m[axis] * 100.;
        context.direction[axis] =
            event.particle.direction[axis];
      }
      context.time_s = event.particle.time_s;

      proposal::ProposalRandomKey const random_key{
          random_seed,
          shower_id,
          event.particle.history_id,
          event.particle.step_id,
          event.random_process_id != 0u
              ? event.random_process_id
              : static_cast<std::uint32_t>(event.process_id),
          event.random_draw_id};
      return proposal::ProposalInteractionRecord{
          context,
          static_cast<std::size_t>(event.interaction_hash),
          static_cast<PROPOSAL::InteractionType>(
              event.process_id),
          static_cast<std::size_t>(event.component_hash),
          event.energy_fraction,
          event.selection_uniform,
          random_key};
    }

  } // namespace proposal_fallback_detail

  /**
   * Convert the device fallback record to the existing CPU-side specified
   * interaction record. Position is converted m -> cm and energy GeV -> MeV.
   */
  inline proposal::ProposalInteractionRecord
  makeProposalInteractionRecord(
      ProposalFallbackEvent const& event,
      std::uint64_t random_seed,
      std::uint64_t shower_id) {
    if (!hasSpecifiedProposalFinalState(event)) {
      throw std::invalid_argument(
          "GPU fallback does not contain a fully specified PROPOSAL final state");
    }
    return proposal_fallback_detail::makeRecordFromIdentity(
        event, random_seed, shower_id);
  }

  /**
   * Convert an interaction whose process/component are specified but whose
   * fractional loss must still be completed by CPU PROPOSAL.
   */
  inline proposal::ProposalInteractionRecord
  makeProposalInteractionRecordForSelectedLoss(
      ProposalFallbackEvent const& event,
      std::uint64_t random_seed,
      std::uint64_t shower_id) {
    if (!hasResolvableProposalSelectedLoss(event)) {
      throw std::invalid_argument(
          "GPU fallback does not contain a resolvable selected PROPOSAL loss");
    }
    return proposal_fallback_detail::makeRecordFromIdentity(
        event, random_seed, shower_id);
  }

  inline std::vector<double>
  makeProposalFinalStateRandomNumbers(
      ProposalFallbackEvent const& event,
      std::size_t count,
      std::uint64_t random_seed,
      std::uint64_t shower_id) {
    if (!hasSpecifiedProposalFinalState(event) &&
        !hasResolvableProposalSelectedLoss(event)) {
      throw std::invalid_argument(
          "cannot draw a PROPOSAL final state for an unresolved GPU fallback");
    }
    if (count >
        std::numeric_limits<std::uint64_t>::max() -
            CpuProposalFinalStateDrawIdBase) {
      throw std::overflow_error(
          "PROPOSAL final-state random-number count overflow");
    }
    std::vector<double> random_numbers(count);
    for (std::size_t index = 0; index < count; ++index) {
      RandomNumberKey const key{
          random_seed,
          shower_id,
          event.particle.history_id,
          event.particle.step_id,
          static_cast<std::uint32_t>(event.process_id),
          CpuProposalFinalStateDrawIdBase +
              static_cast<std::uint64_t>(index)};
      random_numbers[index] = uniformOpen01(key);
    }
    return random_numbers;
  }

  /**
   * Complete a device-selected fallback with an InteractionModel-compatible
   * CPU generator. The model validates the medium and interaction hashes,
   * then calls only the specified final-state calculator.
   */
  template <typename TProposalInteractionModel>
  auto generateSpecifiedProposalFinalState(
      TProposalInteractionModel& model,
      ProposalFallbackEvent const& event,
      std::uint64_t random_seed,
      std::uint64_t shower_id) {
    auto const record = makeProposalInteractionRecord(
        event, random_seed, shower_id);
    auto const count =
        model.requiredFinalStateRandomNumbers(record);
    auto random_numbers =
        makeProposalFinalStateRandomNumbers(
            event, count, random_seed, shower_id);
    return model.generateFinalState(
        record, std::move(random_numbers));
  }

} // namespace corsika::gpu::em
