#!/usr/bin/env python3
"""
Run a reproducible scalar-PROPOSAL versus CUDA-EM performance acceptance.

The application-level wall clock includes common model initialization.  The
SimulationTiming output added to c8_air_shower supplies a second, backend-
neutral measurement from OutputManager::startOfShower through endOfShower.
Both numbers are retained; neither is inferred from CUDA event totals.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import shlex
import statistics
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

import yaml


MOLIERE_CACHE_SUFFIX = ".moliere-initial-v1.c8cache"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Benchmark scalar PROPOSAL and CUDA EM with identical shower settings."
    )
    parser.add_argument("--executable", type=Path, required=True)
    parser.add_argument("--table", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    parser.add_argument("--energy-gev", type=float, default=1.0e6)
    parser.add_argument("--events", type=int, default=1)
    parser.add_argument(
        "--repetitions",
        type=int,
        default=5,
        help=(
            "Number of independent process-level CPU/CUDA repetitions. "
            "The acceptance speedup is the ratio of the two median timings."
        ),
    )
    parser.add_argument("--seed", type=int, default=24027)
    parser.add_argument("--primary-pdg", type=int, default=11)
    parser.add_argument("--em-cut-gev", type=float, default=0.5e-3)
    parser.add_argument("--em-thinning", type=float, default=1.0e-4)
    parser.add_argument("--maximum-weight", type=float, default=100.0)
    parser.add_argument(
        "--non-em-cut-gev",
        type=float,
        default=1.0e13,
        help="Common hadron/muon/tau cut used to isolate the EM cascade.",
    )
    parser.add_argument(
        "--mu-cut-gev",
        type=float,
        default=None,
        help=(
            "Optional separate muon cut. Use the cut recorded by a "
            "muon-enabled CUDA table while retaining high hadron/tau cuts "
            "for a pure-EM benchmark."
        ),
    )
    parser.add_argument("--gpu-device", type=int, default=0)
    parser.add_argument("--gpu-min-batch", type=int, default=64)
    parser.add_argument("--gpu-table-tolerance", type=float, default=1.0e-3)
    parser.add_argument("--ring", type=int, default=0)
    parser.add_argument(
        "--minimum-speedup",
        type=float,
        default=0.0,
        help="Fail when the summed per-shower timing speedup is below this value.",
    )
    parser.add_argument(
        "--skip-cache-warmup",
        action="store_true",
        help=(
            "Deprecated alias for --cache-mode as-is. Do not create the "
            "auxiliary Moliere cache before the timed CUDA run."
        ),
    )
    parser.add_argument(
        "--cache-mode",
        choices=("warm", "as-is", "cold-first", "cold-each"),
        default=None,
        help=(
            "Auxiliary Moliere-cache policy. warm guarantees a pre-existing "
            "cache; as-is preserves the current state; cold-first requires an "
            "initially absent cache; cold-each additionally removes only the "
            "cache generated by the preceding timed repetition. Cold modes "
            "refuse to remove a cache that existed before the benchmark."
        ),
    )
    parser.add_argument(
        "--require-release-build",
        action="store_true",
        help=(
            "Require the executable to live below a CMake build tree whose "
            "CMAKE_BUILD_TYPE is exactly Release."
        ),
    )
    return parser.parse_args()


def validate_arguments(args: argparse.Namespace) -> None:
    if not args.executable.is_file():
        raise ValueError(f"executable is not a regular file: {args.executable}")
    if not args.table.is_file():
        raise ValueError(f"rate table is not a regular file: {args.table}")
    if args.output_root.exists():
        raise ValueError(
            f"output root already exists; refusing to overwrite: {args.output_root}"
        )
    if args.energy_gev <= 0 or args.events <= 0 or args.repetitions <= 0:
        raise ValueError("energy, event count and repetition count must be positive")
    if (
        args.em_cut_gev <= 0
        or args.non_em_cut_gev <= 0
        or (
            getattr(args, "mu_cut_gev", None) is not None
            and args.mu_cut_gev <= 0
        )
    ):
        raise ValueError("particle cuts must be positive")
    if not 0.0 <= args.em_thinning <= 1.0:
        raise ValueError("EM thinning fraction must be in [0, 1]")
    if args.maximum_weight <= 0:
        raise ValueError("maximum weight must be positive")
    if (
        args.skip_cache_warmup
        and args.cache_mode is not None
        and args.cache_mode != "as-is"
    ):
        raise ValueError(
            "--skip-cache-warmup may only be combined with --cache-mode as-is"
        )


def requested_cache_mode(args: argparse.Namespace) -> str:
    if args.cache_mode is not None:
        return str(args.cache_mode)
    return "as-is" if args.skip_cache_warmup else "warm"


def common_command(args: argparse.Namespace, output: Path) -> list[str]:
    mu_cut_gev = (
        args.non_em_cut_gev
        if getattr(args, "mu_cut_gev", None) is None
        else args.mu_cut_gev
    )
    return [
        str(args.executable),
        "-p",
        str(args.primary_pdg),
        "-E",
        f"{args.energy_gev:.17g}",
        "-N",
        str(args.events),
        "-f",
        str(output),
        "--ring",
        str(args.ring),
        "--seed",
        str(args.seed),
        "--emcut",
        f"{args.em_cut_gev:.17g}",
        "--emthin",
        f"{args.em_thinning:.17g}",
        "--max-weight",
        f"{args.maximum_weight:.17g}",
        "--hadcut",
        f"{args.non_em_cut_gev:.17g}",
        "--mucut",
        f"{mu_cut_gev:.17g}",
        "--taucut",
        f"{args.non_em_cut_gev:.17g}",
        "--verbosity",
        "warn",
    ]


def gpu_command(args: argparse.Namespace, output: Path) -> list[str]:
    return common_command(args, output) + [
        "--em-backend",
        "cuda",
        "--radio-backend",
        "cuda",
        "--gpu-device",
        str(args.gpu_device),
        "--gpu-min-batch",
        str(args.gpu_min_batch),
        "--gpu-table-cache",
        str(args.table),
        "--gpu-table-tolerance",
        f"{args.gpu_table_tolerance:.17g}",
        "--gpu-detailed-stage-timing",
    ]


def cpu_command(args: argparse.Namespace, output: Path) -> list[str]:
    return common_command(args, output) + [
        "--em-backend",
        "proposal",
        "--radio-backend",
        "cpu",
    ]


def single_thread_environment() -> dict[str, str]:
    environment = os.environ.copy()
    environment.update(
        {
            "OMP_NUM_THREADS": "1",
            "OPENBLAS_NUM_THREADS": "1",
            "MKL_NUM_THREADS": "1",
            "NUMEXPR_NUM_THREADS": "1",
        }
    )
    return environment


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def artifact_identity(path: Path) -> dict[str, Any]:
    resolved = path.resolve()
    status = resolved.stat()
    return {
        "path": str(resolved),
        "size_bytes": status.st_size,
        "mtime_ns": status.st_mtime_ns,
        "sha256": sha256_file(resolved),
    }


def verify_artifact_identity(
    expected: dict[str, Any],
    label: str,
) -> None:
    observed = artifact_identity(Path(expected["path"]))
    if (
        observed["size_bytes"] != expected["size_bytes"]
        or observed["sha256"] != expected["sha256"]
    ):
        raise RuntimeError(
            f"{label} changed while performance repetitions were running; "
            "benchmark is invalid"
        )


def cmake_build_provenance(executable: Path) -> dict[str, Any]:
    """Find and parse the nearest CMakeCache.txt above an executable."""
    for directory in (executable.parent, *executable.parents):
        cache_path = directory / "CMakeCache.txt"
        if not cache_path.is_file():
            continue
        values: dict[str, str] = {}
        with cache_path.open("r", encoding="utf-8", errors="replace") as source:
            for raw_line in source:
                line = raw_line.strip()
                if not line or line.startswith(("#", "//")) or "=" not in line:
                    continue
                typed_key, value = line.split("=", 1)
                key = typed_key.split(":", 1)[0]
                if key in {
                    "CMAKE_BUILD_TYPE",
                    "CMAKE_CXX_COMPILER",
                    "CMAKE_CUDA_COMPILER",
                    "CMAKE_CUDA_ARCHITECTURES",
                }:
                    values[key] = value
        return {
            "cmake_cache_found": True,
            "cmake_cache": str(cache_path.resolve()),
            "build_type": values.get("CMAKE_BUILD_TYPE", ""),
            "cxx_compiler": values.get("CMAKE_CXX_COMPILER", ""),
            "cuda_compiler": values.get("CMAKE_CUDA_COMPILER", ""),
            "cuda_architectures": values.get("CMAKE_CUDA_ARCHITECTURES", ""),
        }
    return {
        "cmake_cache_found": False,
        "cmake_cache": None,
        "build_type": None,
        "cxx_compiler": None,
        "cuda_compiler": None,
        "cuda_architectures": None,
    }


def run_command(
    command: list[str],
    log_path: Path,
    environment: dict[str, str],
) -> float:
    started = time.perf_counter()
    with log_path.open("w", encoding="utf-8") as log:
        completed = subprocess.run(
            command,
            stdout=log,
            stderr=subprocess.STDOUT,
            env=environment,
            check=False,
        )
    elapsed = time.perf_counter() - started
    if completed.returncode != 0:
        raise RuntimeError(
            f"command failed with exit code {completed.returncode}: "
            f"{shlex.join(command)}; see {log_path}"
        )
    return elapsed


def read_shower_times(output: Path) -> list[float]:
    summary_path = output / "simulation_timing" / "summary.yaml"
    with summary_path.open("r", encoding="utf-8") as source:
        summary = yaml.safe_load(source)
    if not isinstance(summary, dict):
        raise RuntimeError(f"invalid timing summary: {summary_path}")
    times: list[float] = []
    for shower_name in sorted(summary):
        record = summary[shower_name]
        if (
            not isinstance(record, dict)
            or record.get("closed") is not True
            or record.get("status") != "closed"
        ):
            raise RuntimeError(
                f"timing record is incomplete: {summary_path}:{shower_name}"
            )
        times.append(float(record["wall_time_ms"]))
    if not times:
        raise RuntimeError(f"timing summary contains no showers: {summary_path}")
    return times


def timing_statistics(times_ms: list[float]) -> dict[str, Any]:
    return {
        "events": len(times_ms),
        "sum_ms": sum(times_ms),
        "mean_ms": statistics.fmean(times_ms),
        "median_ms": statistics.median(times_ms),
        "minimum_ms": min(times_ms),
        "maximum_ms": max(times_ms),
        "per_shower_ms": times_ms,
    }


def sample_statistics(values: list[float], unit: str) -> dict[str, Any]:
    if not values:
        raise ValueError("cannot summarize an empty timing sample")
    if any(not math.isfinite(value) or value < 0.0 for value in values):
        raise ValueError("timing samples must be non-negative finite numbers")
    return {
        "unit": unit,
        "count": len(values),
        "median": statistics.median(values),
        "mean": statistics.fmean(values),
        "minimum": min(values),
        "maximum": max(values),
        "samples": values,
    }


def aggregate_repetitions(samples: list[dict[str, Any]]) -> dict[str, Any]:
    if not samples:
        raise ValueError("cannot aggregate an empty benchmark")

    proposal_external = [
        float(sample["proposal"]["external_wall_seconds"]) for sample in samples
    ]
    cuda_external = [
        float(sample["cuda"]["external_wall_seconds"]) for sample in samples
    ]
    proposal_shower = [
        float(sample["proposal"]["shower_timing"]["sum_ms"]) for sample in samples
    ]
    cuda_shower = [
        float(sample["cuda"]["shower_timing"]["sum_ms"]) for sample in samples
    ]
    if any(value <= 0.0 for value in cuda_external + cuda_shower):
        raise ValueError("CUDA timings must be positive before computing speedup")
    paired_external = [
        cpu / gpu
        for cpu, gpu in zip(proposal_external, cuda_external)
    ]
    paired_shower = [
        cpu / gpu
        for cpu, gpu in zip(proposal_shower, cuda_shower)
    ]

    proposal_external_summary = sample_statistics(proposal_external, "s")
    cuda_external_summary = sample_statistics(cuda_external, "s")
    proposal_shower_summary = sample_statistics(proposal_shower, "ms")
    cuda_shower_summary = sample_statistics(cuda_shower, "ms")
    external_speedup = (
        proposal_external_summary["median"] / cuda_external_summary["median"]
    )
    shower_speedup = (
        proposal_shower_summary["median"] / cuda_shower_summary["median"]
    )
    return {
        "proposal": {
            "external_wall": proposal_external_summary,
            "summed_shower_timing": proposal_shower_summary,
        },
        "cuda": {
            "external_wall": cuda_external_summary,
            "summed_shower_timing": cuda_shower_summary,
        },
        "speedup": {
            "definition": "ratio_of_backend_medians",
            "external_wall": external_speedup,
            "summed_shower_timing": shower_speedup,
            "paired_external_wall": sample_statistics(paired_external, "ratio"),
            "paired_summed_shower_timing": sample_statistics(
                paired_shower, "ratio"
            ),
        },
    }


def warm_cache(
    args: argparse.Namespace,
    root: Path,
    environment: dict[str, str],
) -> dict[str, Any]:
    cache_path = Path(str(args.table) + MOLIERE_CACHE_SUFFIX)
    if cache_path.is_file():
        return {
            "required": True,
            "performed": False,
            "cache_path": str(cache_path),
            "cache_bytes": cache_path.stat().st_size,
        }
    warmup_output = root / "cache_warmup"
    warmup_command = gpu_command(args, warmup_output)
    # A low-energy event initializes and validates the exact same snapshot and
    # cache without making the production benchmark itself a cold-cache run.
    energy_index = warmup_command.index("-E") + 1
    events_index = warmup_command.index("-N") + 1
    warmup_command[energy_index] = "10"
    warmup_command[events_index] = "1"
    elapsed = run_command(
        warmup_command,
        root / "cache_warmup.log",
        environment,
    )
    if not cache_path.is_file():
        raise RuntimeError(f"CUDA warmup did not create Moliere cache: {cache_path}")
    return {
        "mode": "warm",
        "required": True,
        "performed": True,
        "wall_seconds": elapsed,
        "cache_path": str(cache_path),
        "cache_bytes": cache_path.stat().st_size,
        "command": warmup_command,
    }


def configure_cache(
    args: argparse.Namespace,
    root: Path,
    environment: dict[str, str],
) -> dict[str, Any]:
    mode = requested_cache_mode(args)
    cache_path = Path(str(args.table) + MOLIERE_CACHE_SUFFIX)
    if mode == "warm":
        result = warm_cache(args, root, environment)
        result["mode"] = mode
        result["initially_present"] = True
        result["runs"] = []
        return result

    initially_present = cache_path.is_file()
    if mode in {"cold-first", "cold-each"} and initially_present:
        raise ValueError(
            f"--cache-mode {mode} requires an initially absent derived cache; "
            f"refusing to remove pre-existing file: {cache_path}. Copy the "
            "immutable rate table to a fresh benchmark directory first."
        )
    return {
        "mode": mode,
        "required": False,
        "performed": False,
        "cache_path": str(cache_path),
        "initially_present": initially_present,
        "runs": [],
    }


def prepare_cuda_cache(
    cache: dict[str, Any],
    repetition: int,
) -> dict[str, Any]:
    mode = str(cache["mode"])
    cache_path = Path(str(cache["cache_path"]))
    present_before_prepare = cache_path.is_file()
    removed = False
    if mode == "cold-each":
        if repetition == 0:
            if present_before_prepare:
                raise RuntimeError(
                    "cold-each cache unexpectedly exists before repetition 0"
                )
        else:
            if not present_before_prepare:
                raise RuntimeError(
                    "cold-each cache was not generated by the preceding CUDA run"
                )
            cache_path.unlink()
            removed = True
    elif mode == "cold-first" and repetition == 0 and present_before_prepare:
        raise RuntimeError(
            "cold-first cache unexpectedly exists before repetition 0"
        )
    elif mode == "warm" and not present_before_prepare:
        raise RuntimeError("warm cache disappeared before a timed CUDA run")

    return {
        "mode": mode,
        "repetition": repetition,
        "present_before_prepare": present_before_prepare,
        "removed_before_run": removed,
        "present_before_run": cache_path.is_file(),
    }


def finish_cuda_cache(
    cache: dict[str, Any],
    run_record: dict[str, Any],
) -> None:
    cache_path = Path(str(cache["cache_path"]))
    present_after_run = cache_path.is_file()
    run_record["present_after_run"] = present_after_run
    run_record["cache_bytes_after_run"] = (
        cache_path.stat().st_size if present_after_run else 0
    )
    if cache["mode"] in {"warm", "cold-first", "cold-each"}:
        if not present_after_run:
            raise RuntimeError(
                f"{cache['mode']} benchmark did not leave a valid Moliere cache"
            )
    cache["runs"].append(run_record)


def main() -> int:
    args = parse_args()
    validate_arguments(args)
    args.executable = args.executable.resolve()
    args.table = args.table.resolve()
    args.output_root = args.output_root.resolve()
    build = cmake_build_provenance(args.executable)
    artifacts = {
        "executable": artifact_identity(args.executable),
        "table": artifact_identity(args.table),
        "runner": artifact_identity(Path(__file__)),
    }
    if args.require_release_build and build["build_type"] != "Release":
        raise ValueError(
            "--require-release-build requested, but the nearest CMake cache "
            f"reports build type {build['build_type']!r}: "
            f"{build['cmake_cache']}"
        )
    args.output_root.mkdir(parents=True)

    environment = single_thread_environment()
    flupro = environment.get("FLUPRO")
    cache = configure_cache(
        args, args.output_root, environment
    )

    samples: list[dict[str, Any]] = []
    for repetition in range(args.repetitions):
        repetition_root = args.output_root / f"repetition_{repetition:03d}"
        repetition_root.mkdir()
        cpu_output = repetition_root / "proposal"
        gpu_output = repetition_root / "cuda"
        cpu = cpu_command(args, cpu_output)
        gpu = gpu_command(args, gpu_output)

        # Alternating the order avoids granting either backend the same thermal
        # and filesystem-cache position in all process-level repetitions.
        backend_order = (
            ("proposal", cpu, repetition_root / "proposal.log")
            if repetition % 2 == 0
            else ("cuda", gpu, repetition_root / "cuda.log")
        )
        other_backend = (
            ("cuda", gpu, repetition_root / "cuda.log")
            if repetition % 2 == 0
            else ("proposal", cpu, repetition_root / "proposal.log")
        )
        external: dict[str, float] = {}
        cache_run: dict[str, Any] | None = None
        for backend, command, log_path in (backend_order, other_backend):
            if backend == "cuda":
                cache_run = prepare_cuda_cache(cache, repetition)
            external[backend] = run_command(command, log_path, environment)
            if backend == "cuda":
                assert cache_run is not None
                finish_cuda_cache(cache, cache_run)

        cpu_times = read_shower_times(cpu_output)
        gpu_times = read_shower_times(gpu_output)
        if len(cpu_times) != len(gpu_times):
            raise RuntimeError(
                "CPU and CUDA timing summaries have different event counts "
                f"in repetition {repetition}"
            )
        if len(cpu_times) != args.events:
            raise RuntimeError(
                f"repetition {repetition} produced {len(cpu_times)} timing records; "
                f"expected {args.events}"
            )

        cpu_statistics = timing_statistics(cpu_times)
        gpu_statistics = timing_statistics(gpu_times)
        samples.append(
            {
                "index": repetition,
                "execution_order": [
                    backend_order[0],
                    other_backend[0],
                ],
                "commands": {
                    "proposal": cpu,
                    "cuda": gpu,
                },
                "proposal": {
                    "external_wall_seconds": external["proposal"],
                    "shower_timing": cpu_statistics,
                },
                "cuda": {
                    "external_wall_seconds": external["cuda"],
                    "shower_timing": gpu_statistics,
                    "cache": cache_run,
                },
                "speedup": {
                    "external_wall": (
                        external["proposal"] / external["cuda"]
                    ),
                    "summed_shower_timing": (
                        cpu_statistics["sum_ms"] /
                        gpu_statistics["sum_ms"]
                    ),
                },
            }
        )

    aggregate = aggregate_repetitions(samples)
    verify_artifact_identity(
        artifacts["executable"],
        "c8_air_shower executable",
    )
    verify_artifact_identity(
        artifacts["table"],
        "CUDA EM table",
    )
    event_speedup = aggregate["speedup"]["summed_shower_timing"]
    passed = (
        args.minimum_speedup <= 0.0
        or event_speedup >= args.minimum_speedup
    )
    result = {
        "status": "passed" if passed else "failed",
        "configuration": {
            "energy_GeV": args.energy_gev,
            "events": args.events,
            "repetitions": args.repetitions,
            "seed": args.seed,
            "primary_pdg": args.primary_pdg,
            "em_cut_GeV": args.em_cut_gev,
            "em_thinning": args.em_thinning,
            "maximum_weight": args.maximum_weight,
            "non_em_cut_GeV": args.non_em_cut_gev,
            "mu_cut_GeV": (
                args.non_em_cut_gev
                if getattr(args, "mu_cut_gev", None) is None
                else args.mu_cut_gev
            ),
            "ring": args.ring,
            "minimum_speedup": args.minimum_speedup,
            "require_release_build": args.require_release_build,
            "build": build,
            "single_thread_environment": {
                key: environment[key]
                for key in (
                    "OMP_NUM_THREADS",
                    "OPENBLAS_NUM_THREADS",
                    "MKL_NUM_THREADS",
                    "NUMEXPR_NUM_THREADS",
                )
            },
            "fluka_environment": {
                "FLUPRO": flupro,
                "FLUPRO_is_directory": bool(
                    flupro and Path(flupro).is_dir()
                ),
            },
        },
        "artifact_identity": artifacts,
        "cache": cache,
        "samples": samples,
        "aggregate": aggregate,
        # Keep the established speedup path stable for existing report readers.
        "speedup": aggregate["speedup"],
    }
    summary_path = args.output_root / "benchmark_summary.json"
    with summary_path.open("w", encoding="utf-8") as destination:
        json.dump(result, destination, indent=2)
        destination.write("\n")
    print(json.dumps(result["speedup"], indent=2))
    print(f"summary: {summary_path}")
    return 0 if passed else 2


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, ValueError) as error:
        print(f"performance acceptance failed: {error}", file=sys.stderr)
        raise SystemExit(1)
