// Experiment-only event lifecycle hook. The original SIBYLL physics objects
// are linked unchanged; gasdev.f keeps one Box-Muller spare in /RNDMGAS/.
// A new event RNG must not consume a spare generated by the preceding event.
extern "C" {
extern struct { int iset; } rndmgas_;
void egs4_reset_sibyll_gaussian_cache() { rndmgas_.iset = 0; }
}
