// Also compile with -DC8_CURVED_HOST_ONLY for a dependency-free scalar oracle.
#ifndef C8_CURVED_HOST_ONLY
#include <Kokkos_Core.hpp>
#include <corsika/geometry/terrain/KokkosTerrainSession.hpp>
#endif
#include <corsika/geometry/terrain/FlatTerrainData.hpp>
#include <corsika/geometry/terrain/TerrainCurvedBoundary.hpp>
#include <algorithm>
#include <array>
#include <iomanip>
#include <iostream>
#include <random>
#include <vector>
namespace t= corsika::terrain;
namespace f= t::flat;

namespace {
t::FlatTerrainData plane() {
  t::FlatTerrainData m;
  m.vertices={{-1,-1,0},{1,-1,0},{1,1,0},{-1,1,0}};
  for(auto ids:std::array<std::array<std::uint32_t,3>,2>{{{0,1,2},{0,2,3}}}) {
    auto o=m.vertices[ids[0]];
    m.triangles.push_back({o,f::sub(m.vertices[ids[1]],o),f::sub(m.vertices[ids[2]],o),{0,0,1}});
    m.indexed_triangles.push_back({{ids[0],ids[1],ids[2]},{0,0,1}});
    m.indices.push_back(m.indices.size());
  }
  m.nodes.push_back({{-1,-1,0},{1,1,0},1,0,2});
  return m;
}
struct Case { char const* name; f::QuadraticPath path;std::uint32_t face;double distance,tolerance; };
std::vector<Case> cases() {
  std::vector<Case> c;
  // Nonzero curvature perpendicular to the initial direction. The root is
  // exactly 1 m and the true projected x can differ from y by one binary64 ULP.
  for(auto target:std::array<std::pair<double,std::uint32_t>,3>{{
      {.25,0},{std::nextafter(.25,1.),0},{std::nextafter(.25,0.),1}}})
    c.push_back({"edge-side",{{{target.first-.03125,.25,1},{0,0,-1},false},{.03125,0,0},1.5},target.second,1.,1.e-15});
  c.push_back({"vertex",{{{1.-.03125,1.,1.},{0,0,-1},false},{.03125,0,0},1.5},0,1.,1.e-15});
  c.push_back({"minimum-flight-budget",{{{.25,0,0},{0,0,-1},false},{.03125,0,0},.5e-9},f::NoTriangle,0.,0.});
  // A physically possible near-grazing parabola: d.q=0, |d|=1.  The
  // naive b*b-4*a*c is zero although the exact binary64-input discriminant >0.
  double a=.003,b=-.001,z=8.333333333333333e-5,dx=std::sqrt(1.-b*b);
  // Golden binary64 root independently computed at 100 decimal digits from
  // Decimal.from_float(a/b/z), NOT from their rounded decimal spellings.
  // Long double alone loses accuracy in this deliberately cancelled case.
  double root=0x1.5555552b2b6cfp-3;
  c.push_back({"near-tangent-two-roots",{{{0,0,z},{dx,0,b},false},{-b*a/dx,0,a},.2},0,root,0.});
  c.push_back({"tangent",{{{.25,0,.125},{0,0,-.25},false},{0,0,.125},2.},f::NoTriangle,0.,0.});
  c.push_back({"two-roots-entry",{{{.25,0,.09375},{0,0,-.25},false},{0,0,.125},2.},0,.5,1.e-15});
  c.push_back({"two-roots-exit",{{{.25,0,.09375},{0,0,-.25},true},{0,0,.125},2.},0,1.5,1.e-15});
  c.push_back({"negative-discriminant",{{{.25,0,std::nextafter(.125,1.)},{0,0,-.25},false},{0,0,.125},2.},f::NoTriangle,0.,0.});
  c.push_back({"before-first-root",{{{.25,0,.09375},{0,0,-.25},false},{0,0,.125},.49},f::NoTriangle,0.,0.});
  c.push_back({"zero-curvature",{{{.25,0,1.},{0,0,-1.},false},{0,0,0},2.},0,1.,1.e-15});
  c.push_back({"zero-interval",{{{.25,0,1.},{0,0,-1.},false},{.03125,0,0},0.},f::NoTriangle,0.,0.});
  // Independent long-double oracle, away from edge/tangent ambiguities.
  // Every path has |d|=1 and d.q=0 up to input rounding. No hit generated by
  // the implementation under test is used as its expected answer.
  std::mt19937_64 rng(2026090901);std::uniform_real_distribution<double> u(0.,1.);
  for(std::size_t i=0;i<1000000;++i) {
    double b=-.2-.7*u(rng),a=.001+.009*u(rng),z=.001+.009*u(rng);
    double dx=std::sqrt(1.-b*b);
    long double disc=(long double)b*b-4.L*a*z;
    double root=static_cast<double>(2.L*z/(-(long double)b+std::sqrt(disc)));
    c.push_back({"random",{{{.25,0,z},{dx,0,b},false},{-b*a/dx,0,a},.1},0,root,2.e-15});
  }
  return c;
}
#ifndef C8_CURVED_HOST_ONLY
using Space=Kokkos::DefaultExecutionSpace;
using Paths=Kokkos::View<f::QuadraticPath*,Space::memory_space>;
using Hits=Kokkos::View<f::BoundaryCandidate*,Space::memory_space>;
struct Kernel {
  f::View mesh;Paths paths;Hits results;
  KOKKOS_INLINE_FUNCTION void operator()(std::size_t i)const {results(i)=f::nextCurvedBoundary(mesh,paths(i));}
};
#endif
}
int main() {
  try {
#ifndef C8_CURVED_HOST_ONLY
    Kokkos::ScopeGuard runtime;
    std::cout<<"execution_space="<<Space::name()<<'\n';
#else
    std::cout<<"execution_space=host-only (no device execution)\n";
#endif
    std::size_t failures=0,exactMismatches=0,checks=0;
    double maximumError=0.;
    for(int fixture=0;fixture<2;++fixture) {
    auto m=plane();std::vector<Case> queries;
    if(fixture==0)queries=cases();
    else {
      // Non-coplanar faces: the original shared vertex need not lie on the
      // plane reconstructed from a rounded unit normal and another vertex.
      m.vertices={{-.7,-.9,.2},{.9,-.8,-.1},{0,0,0},{-.8,.9,.4}};
      for(std::size_t i=0;i<m.triangles.size();++i) {
        auto& tri=m.indexed_triangles[i];auto o=m.vertices[tri.vertex[0]];
        auto e1=f::sub(m.vertices[tri.vertex[1]],o),e2=f::sub(m.vertices[tri.vertex[2]],o);
        auto n=f::cross(e1,e2);double length=std::sqrt(f::dot(n,n));
        n={n.x/length,n.y/length,n.z/length};tri.normal=n;
        m.triangles[i]={o,e1,e2,n};
      }
      m.nodes[0].low={-1,-1,-1};m.nodes[0].high={1,1,1};
      for(double l:{1./128.,1./64.,1./32.})for(double s:{-1.,1.})
        queries.push_back({"noncoplanar-vertex",{{{-l*l/64.,0.,-s*l},{0.,0.,s},s>0},{1./64.,0.,0.},2*l},0,l,0.});
    }
    for(int permutation=0;permutation<2;++permutation) {
      if(permutation)std::reverse(m.indices.begin(),m.indices.end());
      std::vector<f::BoundaryCandidate> result;
      for(auto const& q:queries)result.push_back(f::nextCurvedBoundary(m.view(),q.path));
#ifndef C8_CURVED_HOST_ONLY
      t::KokkosTerrainSession<Space> session(m,16);
      Paths input("curved_cases",queries.size());Hits output("curved_results",queries.size());
      auto h=Kokkos::create_mirror_view(input);
      for(std::size_t i=0;i<queries.size();++i)h(i)=queries[i].path;
      Kokkos::deep_copy(input,h);
      Kokkos::parallel_for("curved_regression",Kokkos::RangePolicy<Space>(0,queries.size()),Kernel{session.deviceView(),input,output});
      auto actual=Kokkos::create_mirror_view_and_copy(Kokkos::HostSpace{},output);
      for(std::size_t i=0;i<queries.size();++i) {
        if(actual(i).hit.triangle!=result[i].hit.triangle||actual(i).hit.distance!=result[i].hit.distance||actual(i).crossing!=result[i].crossing)++exactMismatches;
        result[i]=actual(i);
      }
#endif
      for(std::size_t i=0;i<queries.size();++i) {
        auto const& c=queries[i];auto h=result[i];
        ++checks;
        bool pass=h.hit.triangle==c.face&&(c.face==f::NoTriangle||std::abs(h.hit.distance-c.distance)<=c.tolerance);
        if(!pass)++failures;
        if(c.face!=f::NoTriangle)maximumError=std::max(maximumError,std::abs(h.hit.distance-c.distance));
        if(i>=13&&pass)continue;
        if(i>=13&&failures>20)continue;
        std::cout<<std::setprecision(17)<<c.name<<" permutation="<<permutation<<" pass="<<pass
          <<" distance="<<h.hit.distance<<" expected="<<c.distance<<" face="<<h.hit.triangle<<" expected_face="<<c.face<<'\n';
      }
    }
    }
    // Coefficient rescaling must not change roots or overflow the discriminant.
    for(int e:{-400,0,400}) {
      double r[2];int n=t::curved::roots({std::ldexp(.125,e),0.},
          {std::ldexp(-.25,e),0.},{std::ldexp(.09375,e),0.},r);
      if(n!=2||r[0]!=.5||r[1]!=1.5)++failures;
    }
    std::cout<<"checks="<<checks<<" permutations=2 maximum_distance_error_m="
      <<maximumError<<" failures="<<failures<<" host_device_exact_mismatches="<<exactMismatches<<'\n';
    return failures||exactMismatches?1:0;
  }catch(std::exception const& e){std::cerr<<e.what()<<'\n';return 2;}
}
