// Analytic ray fixtures have prescribed Snell angles/interface points. Expected
// rays are NOT generated by replaying the production root solver on the host.
#include <Kokkos_Core.hpp>
#include <corsika/modules/radio/interface/KokkosPropagation.hpp>
#include <corsika/modules/radio/interface/KokkosAccumulator.hpp>
#include <corsika/modules/transport/kokkos/ExecutionSpace.hpp>
#include <corsika/geometry/terrain/KokkosTerrainSession.hpp>
#include <corsika/geometry/terrain/TerrainMagneticAccuracy.hpp>
#include <corsika/accelerator/em/common/UniformMagneticField.hpp>
#include <corsika/modules/transport/detail/InterfaceMagneticPolicy.hpp>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <cstdlib>
namespace ri=corsika::radio::interface;
namespace d=ri::detail;
namespace terrain=corsika::terrain;
using Space=corsika::interfaces::kokkos::ExecutionSpace;
using Memory=Space::memory_space;
void require(bool value,char const* what){if(!value)throw std::runtime_error(what);}
void close(double a,double b,double rel,char const* what){require(std::abs(a-b)<=rel*std::max({std::abs(a),std::abs(b),1.e-30}),what);}
terrain::FlatTerrainData cube(){
  terrain::FlatTerrainData r;
  r.vertices={{-1,-1,-1},{1,-1,-1},{1,1,-1},{-1,1,-1},{-1,-1,1},{1,-1,1},{1,1,1},{-1,1,1}};
  int faces[][3]={{0,2,1},{0,3,2},{4,5,6},{4,6,7},{0,1,5},{0,5,4},{1,2,6},{1,6,5},{2,3,7},{2,7,6},{3,0,4},{3,4,7}};
  for(auto const& f:faces){auto a=r.vertices[f[0]],e1=d::sub(r.vertices[f[1]],a),e2=d::sub(r.vertices[f[2]],a),n=d::unit(d::cross(e1,e2));
    r.triangles.push_back({a,e1,e2,n});r.indexed_triangles.push_back({{unsigned(f[0]),unsigned(f[1]),unsigned(f[2])},n});r.indices.push_back(r.indices.size());}
  // A threaded root with one leaf per face exercises point-query BVH pruning,
  // including zero-width boxes and both triangles on a shared coplanar edge.
  r.nodes.push_back({{-1,-1,-1},{1,1,1},13,0,0});
  for(unsigned i=0;i<12;++i){auto const& t=r.triangles[i];auto a=t.origin,b=d::add(a,t.edge1),c=d::add(a,t.edge2);
    ri::Vec3 low{std::min({a.x,b.x,c.x}),std::min({a.y,b.y,c.y}),std::min({a.z,b.z,c.z})};
    ri::Vec3 high{std::max({a.x,b.x,c.x}),std::max({a.y,b.y,c.y}),std::max({a.z,b.z,c.z})};
    r.nodes.push_back({low,high,i+2,i,1});}
  return r;
}
struct RayKernel {
  d::PropagationView propagation;
  Kokkos::View<ri::RayQuery*,Memory> queries;
  Kokkos::View<ri::Path*,Memory> paths;
  KOKKOS_INLINE_FUNCTION void operator()(std::size_t i)const{
    auto q=queries(i);paths(i)=q.source_region==q.observer_region?d::directPath(propagation,q):d::transmittedPath(propagation,q,0);
  }
};
std::vector<ri::Path> rays(ri::PropagationConfig const& c,std::vector<ri::RayQuery> const& input,Space const& execution){
  ri::KokkosPropagation<Space> p(c,{},0,execution);
  Kokkos::View<ri::RayQuery*,Memory> q("interface_radio_test_queries",input.size());
  auto h=Kokkos::create_mirror_view(q);for(std::size_t i=0;i<input.size();++i)h(i)=input[i];
  Kokkos::deep_copy(execution,q,h);
  Kokkos::View<ri::Path*,Memory> out("interface_radio_test_paths",input.size());
  Kokkos::parallel_for("interface_radio_analytic_rays",Kokkos::RangePolicy<Space>(execution,0,input.size()),RayKernel{p.view(),q,out});
  auto host=Kokkos::create_mirror_view(out);Kokkos::deep_copy(execution,host,out);execution.fence();
  std::vector<ri::Path> result(input.size());for(std::size_t i=0;i<input.size();++i)result[i]=host(i);return result;
}
struct MeshKernel {
  d::PropagationView propagation;Kokkos::View<ri::Path**,Memory> paths;
  KOKKOS_INLINE_FUNCTION void operator()(std::size_t i)const{
    ri::RayQuery q{{0.,0.,0.},{0.,0.,2.},1,0};
    paths(0,i)=d::transmittedPath(propagation,q,i);
    // Same source/receiver line lies on the shared top edge: count once.
    if(i==0){
      paths(1,0)=d::directPath(propagation,{{-2.,0.,0.},{2.,0.,0.},0,0});
      paths(1,1)=d::directPath(propagation,{{-2.,0.,2.},{2.,0.,2.},0,0});
      paths(1,2)=d::directPath(propagation,{{0.,0.,1.},{0.,0.,2.},0,0});
      paths(1,3)=d::directPath(propagation,{{0.,0.,1.},{0.,0.,-2.},0,0});
    }
  }
};
void checkShallowReciprocity(Space const& execution){
  ri::PropagationConfig c;c.geometry=ri::Geometry::Plane;
  c.media[0].refractive_index=1.000327;c.media[1].refractive_index=2.;
  for(double offset:{0.,2500.})for(double depth:{1.e-6,1.e-4,.01}){
    c.plane_point_m={offset,offset,offset};
    ri::Vec3 source{offset,offset,offset-depth},observer{offset+6000.,offset+3000.,offset+2000.};
    auto paths=rays(c,{{source,observer,1,0},{observer,source,0,1}},execution);
    require(paths[0].status==ri::PathStatus::Valid&&paths[1].status==ri::PathStatus::Valid,"shallow reciprocal Snell solve failed");
    require(std::abs(paths[0].snell_residual)<1.e-10&&std::abs(paths[1].snell_residual)<1.e-10,"shallow reciprocal Snell residual");
    close(paths[0].time_s,paths[1].time_s,1.e-13,"reciprocal optical delay");
    require(d::norm(d::sub(paths[0].interface_point,paths[1].interface_point))<1.e-8,"reciprocal interface point");
    require(d::norm(d::add(paths[0].emit,paths[1].receive_direction))<1.e-10&&d::norm(d::add(paths[0].receive_direction,paths[1].emit))<1.e-10,"reciprocal ray directions");
    close(paths[0].source_length_m,paths[1].destination_length_m,1.e-10,"reciprocal short leg");
  }
}
struct CandidateKernel {
  d::PropagationView propagation;Kokkos::View<ri::Path**,Memory> paths;
  KOKKOS_INLINE_FUNCTION void operator()(std::size_t i)const {
    auto query=i/12,face=i%12;double a=(int(query%17)-8)*.11,b=(int(query%13)-6)*.14;
    ri::Vec3 inside{a,b,.2},outside{(int(query%23)-11)*.4,(int(query%19)-9)*.4,2.+(query%11)};
    if(query%3==1){double t=outside.x;outside.x=outside.z;outside.z=t;}
    if(query%3==2){double t=outside.y;outside.y=-outside.z;outside.z=t;}
    ri::RayQuery q{inside,outside,1,0};
    if(query%2)q={outside,inside,0,1};
    paths(0,i)=d::transmittedPath(propagation,q,face,false,true);
    paths(1,i)=d::transmittedPath(propagation,q,face,false,false);
    paths(2,i)=ri::Path{};
    d::CandidateFaces candidates{propagation,q,false};std::uint32_t id;
    while(candidates.next(id))if(id==face)paths(2,i)=paths(0,i);
  }
};
void checkBufferedSources(Space const& execution){
  using Radio=ri::KokkosAccumulator<Space>;
  ri::Config config;config.enabled=true;config.samples=128;config.start_time_s=0.;
  config.propagation.media[0].refractive_index=1.5;
  config.observers.push_back({"linearity",{10.,0.,0.},0});
  ri::Track track;track.end_m={0.,0.,.1};track.end_time_s=.1/(.99*299792458.);
  track.charge_e=-1.;track.weight=1.;track.valid=1;
  constexpr std::size_t nd=2*ri::DeviceTrackBufferSize+17,nc=ri::DeviceTrackBufferSize+7;
  typename Radio::Tracks input("interface_radio_buffer_test_input",513);
  auto host=Kokkos::create_mirror_view(input);
  for(std::size_t i=0;i<host.extent(0);++i)host(i)=track;
  Kokkos::deep_copy(execution,input,host);execution.fence();
  Radio radio(config,{},0,64,execution);
  for(std::size_t device=0,cpu=0;device<nd||cpu<nc;){
    auto dn=std::min(std::size_t{513},nd-device);
    radio.accumulate(input,dn,execution);device+=dn;
    auto cn=std::min(std::size_t{127},nc-cpu);
    radio.accumulateCpu(std::vector<ri::Track>(cn,track),execution);cpu+=cn;
  }
  auto result=radio.download(execution);
  require(result.statistics.device_tracks==nd&&result.statistics.cpu_tracks==nc,"buffered source accounting");
  require(result.statistics.downloads==1&&!result.statistics.errors,"buffered final download");
  if constexpr(Radio::deviceBuffering)require(result.statistics.wavefronts==5,"buffered full and partial flush count");
  Radio reference(config,{},0,1,execution);track.weight=double(nd+nc);
  reference.accumulateCpu({track},execution);auto expected=reference.download(execution);
  long double difference=0.,norm=0.;
  for(std::size_t i=0;i<result.moments.size();++i){
    long double delta=result.moments[i]-expected.moments[i];
    difference+=delta*delta;norm+=static_cast<long double>(expected.moments[i])*expected.moments[i];
  }
  require(norm>0.&&std::sqrt(difference/norm)<1.e-10,"buffered mixed-source linearity");
  std::cout<<"PASS buffered sources device="<<nd<<" cpu="<<nc<<" radio_batches="<<result.statistics.wavefronts
    <<" relative_l2="<<double(std::sqrt(difference/norm))<<'\n';
}
struct SourceKinematicsKernel {
  Kokkos::View<ri::Track*,Memory> tracks;Kokkos::View<double**,Memory> result;
  KOKKOS_INLINE_FUNCTION void operator()(std::size_t i)const{
    auto t=tracks(i);auto displacement=d::sub(t.end_m,t.start_m);double length=d::norm(displacement),dt=t.end_time_s-t.start_time_s;
    ri::Vec3 beta;bool limited=false;
    bool ok=d::sourceBeta(t,displacement,length,dt,beta,limited);
    result(i,0)=ok;result(i,1)=limited;result(i,2)=ok?d::norm(beta):0.;
  }
};
void checkSourceRoundoff(Space const& execution){
  // Exact rows 11839 / 15603 captured from the first 100 PeV seed 946 run.
  std::vector<ri::Track> data(9);
  data[0].start_m={2516.5338281904737,3921.0693933170355,500.53046668457796};
  data[0].end_m={2516.533828018205,3921.0693649892855,500.53046701621611};
  data[0].start_time_s=1.2440899276040025e-6;data[0].end_time_s=1.2440900221034271e-6;
  data[1].start_m={2516.5371970851511,3921.3554536930696,500.52966734425695};
  data[1].end_m={2516.5371971865275,3921.3554465925231,500.52966735385797};
  data[1].start_time_s=1.2431357330046093e-6;data[1].end_time_s=1.2431357566919185e-6;
  for(unsigned i=0;i<2;++i){data[i].charge_e=-1.;data[i].weight=1.;data[i].valid=1;}
  data[2]=data[0];data[2].end_time_s=data[2].start_time_s+.99*(data[0].end_time_s-data[0].start_time_s);
  data[3]=data[0];data[3].end_time_s=data[3].start_time_s;
  data[4]=data[0];data[4].end_time_s=data[4].start_time_s+2*(data[0].end_time_s-data[0].start_time_s);
  // A 1e-10 relative superluminal excess near the origin is resolved. The old
  // fixed 1e-9 relative allowance would have accepted this malformed source.
  data[5]=data[0];data[5].start_m={0.,0.,0.};data[5].end_m={1.,0.,0.};
  data[5].start_time_s=0.;data[5].end_time_s=1./(299792458.*(1.+1.e-10));
  // Captured tau-shower electron after curved transport: its nanometre-scale
  // chord error uses the transport's pre-existing declared 1e-9 accuracy.
  data[6]=data[0];data[6].start_m={-.1048682405876564,-.074226010634181966,61.962298933055706};
  data[6].end_m={-.41050449772298181,-.2900733397521143,238.43557162505775};
  data[6].start_time_s=2.0671778304108339e-7;data[6].end_time_s=7.9537058150751361e-7;
  data[6].relative_chord_tolerance=1.e-9;data[7]=data[6];data[7].relative_chord_tolerance=0.;
  // Actual late air-shower row 10185957: 0.93 mm excess over 192 m.
  // This resolved integration error MUST NOT be classified as input rounding.
  data[8]=data[6];data[8].start_m={2521.616509630667,-4300.277152537496,492.4444335329587};
  data[8].end_m={2523.579476718079,-4492.113273791829,481.6298749402202};
  data[8].start_time_s=2.8668584942670392e-5;data[8].end_time_s=2.9309527705312035e-5;
  Kokkos::View<ri::Track*,Memory> tracks("radio_roundoff_sources",data.size());
  auto host=Kokkos::create_mirror_view(tracks);for(unsigned i=0;i<data.size();++i)host(i)=data[i];
  Kokkos::deep_copy(execution,tracks,host);
  Kokkos::View<double**,Memory> result("radio_roundoff_result",data.size(),3);
  Kokkos::parallel_for("radio_source_ulp_causality",Kokkos::RangePolicy<Space>(execution,0,data.size()),SourceKinematicsKernel{tracks,result});
  auto h=Kokkos::create_mirror_view(result);Kokkos::deep_copy(execution,h,result);execution.fence();
  for(unsigned i=0;i<2;++i)require(h(i,0)==1.&&h(i,1)==1.&&std::abs(h(i,2)-1.)<1.e-15,"real microscopic source rejected");
  for(unsigned i:{2,3,5,7,8})require(h(i,0)==0.,"source beyond declared accuracy accepted");
  require(h(6,0)==1.&&h(6,1)==1.&&std::abs(h(6,2)-1.)<1.e-15,"declared transport chord accuracy ignored");
  require(h(4,0)==1.&&h(4,1)==0.&&h(4,2)<1.,"subluminal source changed");
  ri::Config c;c.enabled=true;c.samples=4096;c.start_time_s=0.;c.propagation.media[0].refractive_index=1.33;
  c.observers.push_back({"microscopic-source",{2520.,3930.,510.},0});
  ri::KokkosAccumulator<Space,true> paired(c,{},0,2,execution);
  paired.accumulate(tracks,2,execution);auto output=paired.download(execution);
  for(auto const* r:{&output.coreas,&output.zhs})
    require(r->statistics.device_tracks==2&&r->statistics.roundoff_limited_tracks==2&&!r->statistics.errors,"paired microscopic source inventory");
  bool failed=false;
  try{ri::KokkosAccumulator<Space,true> invalid(c,{},0,1,execution);invalid.accumulateCpu({data[2]},execution);invalid.download(execution);}
  catch(std::runtime_error const&){failed=true;}
  require(failed,"paired accumulator silently accepted a resolved acausal source");
  std::cout<<"PASS actual high-energy microscopic sources and resolved acausality rejection\n";
}
struct MagneticAccuracyCase {
  corsika::gpu::em::EmParticleState particle;
  double mass{},charge{},field[3]{},angle{};
};
struct MagneticAccuracyKernel {
  Kokkos::View<MagneticAccuracyCase*,Memory> cases;
  Kokkos::View<double**,Memory> output;
  KOKKOS_INLINE_FUNCTION void operator()(std::size_t i)const {
    namespace em=corsika::gpu::em;
    auto const c=cases(i);
    auto limit=c.angle==.2?em::maximumUniformMagneticStep(c.particle,c.mass,c.charge,c.field,c.angle):
        corsika::interfaces::detail::maximumInterfaceMagneticStep(c.particle,c.mass,c.charge,c.field,c.angle);
    double length=limit.status==em::MagneticStepStatus::Linear?100.:limit.distance_m;
    double zero[3]{0.,0.,0.};
    auto advanced=em::advanceUniformMagneticField(c.particle,c.mass,c.charge,
        limit.status==em::MagneticStepStatus::Linear?zero:c.field,length);
    output(i,0)=length;output(i,1)=advanced.particle.time_s;
    output(i,9)=limit.status==em::MagneticStepStatus::Linear;
    for(unsigned j=0;j<3;++j){output(i,2+j)=advanced.particle.position_m[j];output(i,5+j)=advanced.particle.direction[j];}
    ri::Track source;source.start_m={0.,0.,0.};source.end_m={output(i,2),output(i,3),output(i,4)};
    source.end_time_s=output(i,1);source.relative_chord_tolerance=1.e-9;
    ri::Vec3 beta;bool limited=false;
    output(i,8)=d::sourceBeta(source,source.end_m,d::norm(source.end_m),source.end_time_s,beta,limited);
  }
};
void checkMagneticAccuracy(Space const& execution){
  namespace em=corsika::gpu::em;
  std::vector<MagneticAccuracyCase> cases;
  for(double mass:{5.109989e-4,1.056584e-1})for(double energy:{.3624695166929317,1.,1000.,10000.})
    for(double pitch:{0.,1.e-9,1.e-5,.1,.7071067811865475,1.})for(double charge:{-1.,1.})
      for(double field:{5.e-5,.01})for(double angle:{.2,terrain::MaximumQuadraticMagneticDeflection}){
        MagneticAccuracyCase c;c.mass=mass;c.charge=charge;c.field[2]=field;c.angle=angle;
        c.particle.pid=charge<0?11:-11;c.particle.energy_GeV=energy;c.particle.weight=1.;
        c.particle.direction[0]=pitch;c.particle.direction[2]=std::sqrt(1.-pitch*pitch);cases.push_back(c);
      }
  Kokkos::View<MagneticAccuracyCase*,Memory> input("magnetic_accuracy_cases",cases.size());
  auto h=Kokkos::create_mirror_view(input);for(unsigned i=0;i<cases.size();++i)h(i)=cases[i];Kokkos::deep_copy(execution,input,h);
  Kokkos::View<double**,Memory> output("magnetic_accuracy_results",cases.size(),10);
  Kokkos::parallel_for("interface_magnetic_analytic_helix",Kokkos::RangePolicy<Space>(execution,0,cases.size()),MagneticAccuracyKernel{input,output});
  auto values=Kokkos::create_mirror_view(output);Kokkos::deep_copy(execution,values,output);execution.fence();
  std::ofstream csv;if(auto file=std::getenv("C8_MAGNETIC_ACCURACY_CSV")){csv.open(file);csv<<std::setprecision(17)<<"mass_GeV,energy_GeV,pitch,charge,field_T,angle,length_m,chord_excess,position_error,direction_error,source_accepted\n";}
  unsigned originalRejected=0;double maxPositionError=0.,maxChordExcess=0.;
  for(unsigned i=0;i<cases.size();++i){
    auto const& c=cases[i];double length=values(i,0),pitch=c.particle.direction[0];
    double p=std::sqrt((c.particle.energy_GeV-c.mass)*(c.particle.energy_GeV+c.mass));
    double k=c.charge*em::GeVPerCToTeslaMeter*c.field[2]/p,theta=k*length;
    // Independent closed-form Lorentz-force helix; no production propagator.
    ri::Vec3 exact{pitch*std::sin(theta)/k,-2*pitch*std::pow(std::sin(theta/2),2)/k,c.particle.direction[2]*length};
    ri::Vec3 direction{pitch*std::cos(theta),-pitch*std::sin(theta),c.particle.direction[2]};
    ri::Vec3 actual{values(i,2),values(i,3),values(i,4)},actualDirection{values(i,5),values(i,6),values(i,7)};
    double error=d::norm(d::sub(actual,exact))/length,dirError=d::norm(d::sub(actualDirection,direction));
    double excess=d::norm(actual)/length-1.;
    require(std::isfinite(error)&&std::isfinite(dirError),"nonfinite magnetic helix comparison");
    close(values(i,1),length/(p/c.particle.energy_GeV*d::light_speed),1.e-14,"magnetic flight clock");
    if(c.angle==terrain::MaximumQuadraticMagneticDeflection){
      if(pitch==0.)require(values(i,9)==1.,"field-parallel source has a spurious transverse momentum");
      require(values(i,8)==1.,"accuracy-capped magnetic source violates precision contract");
      require(excess<8.01e-10&&error<1.1e-9&&dirError<1.7e-9,"terrain magnetic accuracy cap does not bound helix error");
      maxPositionError=std::max(maxPositionError,error);maxChordExcess=std::max(maxChordExcess,excess);
    }else if(values(i,8)==0.)++originalRejected;
    if(csv)csv<<c.mass<<','<<c.particle.energy_GeV<<','<<pitch<<','<<c.charge<<','<<c.field[2]<<','<<c.angle<<','<<length<<','<<excess<<','<<error<<','<<dirError<<','<<values(i,8)<<'\n';
  }
  require(originalRejected>0,"magnetic regression did not expose original acausal chords");
  std::cout<<"PASS analytic helix accuracy "<<cases.size()<<" cases; maximum relative position error "<<maxPositionError<<" chord excess "<<maxChordExcess<<'\n';
}
int main(int argc,char** argv){try{
  int threads=256;if(auto e=std::getenv("C8_INTERFACE_TEST_THREADS"))threads=std::stoi(e);
  Kokkos::InitializationSettings settings;settings.set_num_threads(threads);settings.set_device_id(0);
  Kokkos::ScopeGuard guard(settings);Space execution;
  std::ofstream csv;if(argc>1){csv.open(argv[1]);csv<<std::setprecision(17)<<"n_source,n_destination,angle_rad,reverse,source_x,source_z,observer_x,observer_z,interface_error_m,time_s,time_error_s,snell_residual,t_s,t_p,spreading_per_m,transfer_s_per_m\n";}
  std::uint64_t checked=0;
  for(auto indices:std::vector<std::array<double,2>>{{2.,1.},{1.,2.},{1.33,1.},{1.5,1.5}}){
    for(bool reverse:{false,true}){
      ri::PropagationConfig c;c.geometry=ri::Geometry::Plane;c.media[1].refractive_index=indices[0];c.media[0].refractive_index=indices[1];
      double n1=reverse?indices[1]:indices[0],n2=reverse?indices[0]:indices[1];
      std::vector<ri::RayQuery> input;std::vector<long double> expectedTime,angle;
      for(int j=0;j<257;++j){
        long double theta=(n1>n2?std::asin(static_cast<long double>(n2/n1)):std::acos(0.L)/1.01L)*j/258.L;
        long double transmitted=std::asin(n1/n2*std::sin(theta));
        long double ds=1.+j*.071L,dd=2.+j*.029L;
        double sign=reverse?-1.:1.;
        input.push_back({{double(-ds*std::tan(theta)),0.,double(-sign*ds)},
                         {double(dd*std::tan(transmitted)),0.,double(sign*dd)},unsigned(reverse?0:1),unsigned(reverse?1:0)});
        expectedTime.push_back((n1*ds/std::cos(theta)+n2*dd/std::cos(transmitted))/299792458.L);angle.push_back(theta);
      }
      auto output=rays(c,input,execution);
      for(std::size_t j=0;j<output.size();++j){auto const& p=output[j];auto q=input[j];
        require(p.status==ri::PathStatus::Valid,"analytic planar ray failed");
        double error=d::norm(p.interface_point),length=d::norm(d::sub(q.observer,q.source));
        require(error<2.e-10*std::max(1.,length),"prescribed Snell interface point differs");
        close(p.time_s,double(expectedTime[j]),2.e-12,"absolute optical time differs");
        require(std::abs(p.snell_residual)<1.e-11,"Snell residual");
        double ci=std::cos(double(angle[j])),ct=std::sqrt(1.-std::pow(n1/n2*std::sin(double(angle[j])),2));
        double rs=(n1*ci-n2*ct)/(n1*ci+n2*ct),rp=(n2*ci-n1*ct)/(n2*ci+n1*ct),flux=n2*ct/(n1*ci);
        close(rs*rs+flux*p.t_s*p.t_s,1.,3.e-12,"s flux conservation");
        close(rp*rp+flux*p.t_p*p.t_p,1.,3.e-12,"p flux conservation");
        auto incoming=d::unit(d::cross({0.,1.,0.},p.emit));auto outgoing=d::applyTransfer(p,incoming);
        require(std::abs(d::dot(outgoing,p.receive_direction))<1.e-12*d::norm(outgoing),"received polarization not transverse");
        if(n1==n2)close(p.spreading_per_m,1./length,2.e-12,"same material virtual boundary changed amplitude");
        if(csv)csv<<n1<<','<<n2<<','<<double(angle[j])<<','<<reverse<<','<<q.source.x<<','<<q.source.z<<','<<q.observer.x<<','<<q.observer.z<<','<<error<<','<<p.time_s<<','<<p.time_s-double(expectedTime[j])<<','<<p.snell_residual<<','<<p.t_s<<','<<p.t_p<<','<<p.spreading_per_m<<','<<p.transfer_per_m[4]<<'\n';
        ++checked;
      }
    }
  }
  require(!d::fresnel(2.,1.,.5).transmitted,"total internal reflection was transmitted");
  require(d::fresnel(2.,1.,1.).transmitted,"normal incidence missing");
  ri::PropagationConfig uniform;uniform.media[0].refractive_index=1.33;uniform.media[0].attenuation_length_m=100.;
  auto u=rays(uniform,{{{0.,0.,0.},{30.,40.,0.},0,0}},execution).front();
  close(u.time_s,1.33*50./299792458.,1.e-14,"uniform nR/c");close(u.attenuation,std::exp(-.5),1.e-14,"amplitude attenuation");
  // A radial linear index integrates analytically on a radial path.
  uniform.media[0].radial_index={{0.,1.},{1000.,1.01}};
  u=rays(uniform,{{{0.,0.,10.},{0.,0.,510.},0,0}},execution).front();
  close(u.time_s,500.*1.0026/299792458.,3.e-14,"radial optical integral");
  require(rays(uniform,{{{0.,0.,10.},{0.,0.,1100.},0,0}},execution).front().status==ri::PathStatus::Invalid,"out-of-domain optical table accepted");
  // A sharply changing outer atmospheric layer must not be missed by the
  // quadrature. The independent radial reference is an exact trapezoid sum
  // of the piecewise-linear index table on a vertical ray.
  auto layered=uniform;auto& layer=layered.media[0];
  layer.center_m={0.,0.,-6371000.};layer.reference_radius_m=6371000.;
  layer.radial_index={{0.,1.000327},{99999.999999,1.},{100000.,1.000327},{112800.,1.000327}};
  layer.radial_integration_breaks_m={99999.999999,100000.};
  long double exact=0.;
  for(std::size_t i=1;i<layer.radial_index.size();++i){
    auto a=layer.radial_index[i-1],b=layer.radial_index[i];
    long double lo=std::max(3802.,a.height_m),hi=std::min(112799.,b.height_m);
    if(hi<=lo)continue;
    auto index=[&](long double h){return a.index+(b.index-a.index)*(h-a.height_m)/(b.height_m-a.height_m);};
    exact+=(hi-lo)*(index(lo)+index(hi))*.5L;
  }
  u=rays(layered,{{{0.,0.,112799.},{0.,0.,3802.},0,0}},execution).front();
  require(u.status==ri::PathStatus::Valid,"layered long optical path failed");
  close(u.time_s,double(exact/299792458.L),3.e-13,"narrow radial transition quadrature");
  layer.center_m={0.,0.,0.};layer.reference_radius_m=0.;
  layer.radial_index={{0.,1.},{9.999999,1.},{10.000001,2.},{100.,2.}};
  layer.radial_integration_breaks_m={9.999999,10.,10.000001};
  auto bidirectional=rays(layered,{{{-20.,0.,0.},{20.,0.,0.},0,0},{{20.,0.,0.},{-20.,0.,0.},0,0}},execution);
  for(auto const& path:bidirectional)close(path.time_s,60./299792458.,3.e-13,"two crossings of the same radial shell");
  if(argc>3){
    std::ifstream input(argv[2]);ri::PropagationConfig native;auto& medium=native.media[0];std::size_t size=0,breaks=0;
    input>>medium.center_m.x>>medium.center_m.y>>medium.center_m.z>>medium.reference_radius_m>>size>>breaks;
    require(size>=2&&size<=1000000&&breaks<=64,"native optical fixture extent");
    medium.radial_index.resize(size);medium.radial_integration_breaks_m.resize(breaks);
    for(auto& sample:medium.radial_index)input>>sample.height_m>>sample.index;
    for(auto& h:medium.radial_integration_breaks_m)input>>h;
    require(bool(input),"native optical fixture read");
    std::vector<ri::RayQuery> queries;
    for(double height:{7000.,10000.,40000.,100000.,112799.})for(double lateral:{0.,30000.,100000.}){
      double radius=medium.reference_radius_m+height;
      queries.push_back({{medium.center_m.x+lateral,medium.center_m.y,medium.center_m.z+std::sqrt(radius*radius-lateral*lateral)},
        {medium.center_m.x,medium.center_m.y,medium.center_m.z+medium.reference_radius_m+3802.},0,0});
    }
    auto values=rays(native,queries,execution);std::ofstream output(argv[3]);output<<std::setprecision(17)<<"sx,sy,sz,ox,oy,oz,time_s\n";
    for(std::size_t i=0;i<values.size();++i){auto const& p=values[i];auto q=queries[i];require(p.status==ri::PathStatus::Valid,"native long optical ray");
      output<<q.source.x<<','<<q.source.y<<','<<q.source.z<<','<<q.observer.x<<','<<q.observer.y<<','<<q.observer.z<<','<<p.time_s<<'\n';}
  }
  auto mesh=cube();terrain::KokkosTerrainSession<Space> geometry(mesh,1);
  ri::PropagationConfig mc;mc.geometry=ri::Geometry::Mesh;mc.media[1].refractive_index=2.;
  ri::KokkosPropagation<Space> propagation(mc,geometry.deviceView(),mesh.triangles.size(),execution);
  Kokkos::View<ri::Path**,Memory> paths("interface_radio_mesh_paths",2,12);
  Kokkos::parallel_for("interface_radio_mesh_rays",Kokkos::RangePolicy<Space>(execution,0,12),MeshKernel{propagation.view(),paths});
  auto h=Kokkos::create_mirror_view(paths);Kokkos::deep_copy(execution,h,paths);execution.fence();
  unsigned accepted=0;for(int i=0;i<12;++i)if(h(0,i).status==ri::PathStatus::Valid){++accepted;close(h(0,i).time_s,3./299792458.,1.e-14,"mesh absolute delay");}
  require(accepted==1,"shared coplanar face double counted");
  require(h(1,0).status==ri::PathStatus::Blocked,"terrain blocker missed");
  require(h(1,1).status==ri::PathStatus::Valid,"clear air ray rejected");
  require(h(1,2).status==ri::PathStatus::Valid,"surface outward ray rejected");
  require(h(1,3).status==ri::PathStatus::Blocked,"initial surface hid second intersection");
  // Compare the conservative optimization with exhaustive finite-face solving
  // on the device, including both directions and three interface orientations.
  constexpr unsigned candidateQueries=512,candidatePairs=candidateQueries*12;
  Kokkos::View<ri::Path**,Memory> candidates("interface_radio_candidate_paths",3,candidatePairs);
  Kokkos::parallel_for("interface_radio_candidate_equivalence",Kokkos::RangePolicy<Space>(execution,0,candidatePairs),CandidateKernel{propagation.view(),candidates});
  auto ch=Kokkos::create_mirror_view(candidates);Kokkos::deep_copy(execution,ch,candidates);execution.fence();
  unsigned candidateAccepted=0,candidateRejected=0,bvhRejected=0;
  for(unsigned i=0;i<candidatePairs;++i){auto a=ch(0,i),b=ch(1,i);
    require(a.status==b.status,"candidate rejection changed finite-face status");
    if(b.status==ri::PathStatus::Valid||b.status==ri::PathStatus::Blocked)
      require(ch(2,i).status==b.status,"BVH discarded a stationary finite-face path");
    bvhRejected+=ch(2,i).iterations==0&&a.iterations>0;
    if(b.status==ri::PathStatus::Valid){++candidateAccepted;
      require(a.time_s==b.time_s&&a.interface_point.x==b.interface_point.x&&a.interface_point.y==b.interface_point.y&&a.interface_point.z==b.interface_point.z,"candidate rejection changed accepted path");
      for(unsigned j=0;j<9;++j)require(a.transfer_per_m[j]==b.transfer_per_m[j],"candidate rejection changed field transfer");
    }
    candidateRejected+=a.iterations==0&&b.iterations>0;
  }
  require(candidateAccepted>0&&candidateRejected>0&&bvhRejected>0,"candidate fixture did not exercise acceptance and rejection");
  std::cout<<"PASS candidate equivalence pairs="<<candidatePairs<<" valid="<<candidateAccepted<<" avoided_solves="<<candidateRejected<<'\n';
  checkBufferedSources(execution);
  checkShallowReciprocity(execution);
  checkSourceRoundoff(execution);
  checkMagneticAccuracy(execution);
  std::cout<<"PASS interface radio propagation execution="<<Space::name()<<" concurrency="<<execution.concurrency()<<" analytic_rays="<<checked<<" mesh_paths="<<accepted<<'\n';
  return 0;
}catch(std::exception const& e){std::cerr<<e.what()<<'\n';return 1;}}
