/*
 * (c) Copyright 2026 CORSIKA Project, corsika-project@lists.kit.edu
 *
 * This software is distributed under the terms of the 3-clause BSD license.
 * See file LICENSE for a full version of the license.
 */

#pragma once

#include <cstdint>

#include <corsika/gpu/em/Types.hpp>

#if defined(__CUDACC__)
#define CORSIKA_GPU_CAPABILITY_HOST_DEVICE __host__ __device__
#else
#define CORSIKA_GPU_CAPABILITY_HOST_DEVICE
#endif

namespace corsika::gpu::em {

  // PROPOSAL 7.6.2 InteractionType values. Keeping the device library free of
  // PROPOSAL headers avoids exposing its host-only implementation to nvcc.
  inline constexpr std::int32_t BremsProcessId = 1000000002;
  inline constexpr std::int32_t IonizationProcessId = 1000000003;
  inline constexpr std::int32_t ElectronPairProcessId = 1000000004;
  inline constexpr std::int32_t PhotonuclearProcessId = 1000000005;
  inline constexpr std::int32_t MuonPairProcessId = 1000000006;
  inline constexpr std::int32_t HadronsProcessId = 1000000007;
  inline constexpr std::int32_t WeakInteractionProcessId = 1000000009;
  inline constexpr std::int32_t ComptonProcessId = 1000000010;
  inline constexpr std::int32_t DecayProcessId = 1000000011;
  inline constexpr std::int32_t AnnihilationProcessId = 1000000012;
  inline constexpr std::int32_t PhotonPairProcessId = 1000000013;
  // Zero-rate auxiliary table column used only for the independent
  // PhotoPairProductionKochMotzSauter energy split rho(E,u).
  inline constexpr std::int32_t PhotonPairFinalStateProcessId = 2000000013;
  inline constexpr std::int32_t PhotoproductionProcessId = 1000000014;
  inline constexpr std::int32_t PhotonMuonPairProcessId = 1000000015;
  inline constexpr std::int32_t PhotoelectricProcessId = 1000000016;

  inline char const* gpuEmProcessName(std::int32_t process_id) noexcept {
    switch (process_id) {
    case BremsProcessId:
      return "bremsstrahlung";
    case IonizationProcessId:
      return "ionization";
    case ElectronPairProcessId:
      return "electron_pair_production";
    case PhotonuclearProcessId:
      return "photonuclear";
    case MuonPairProcessId:
      return "lepton_muon_pair";
    case HadronsProcessId:
      return "hadrons";
    case WeakInteractionProcessId:
      return "weak_interaction";
    case ComptonProcessId:
      return "compton";
    case DecayProcessId:
      return "decay";
    case AnnihilationProcessId:
      return "annihilation";
    case PhotonPairProcessId:
      return "photon_pair_production";
    case PhotonPairFinalStateProcessId:
      return "photon_pair_final_state";
    case PhotoproductionProcessId:
      return "photoproduction";
    case PhotonMuonPairProcessId:
      return "photon_muon_pair";
    case PhotoelectricProcessId:
      return "photoelectric";
    default:
      return "unknown";
    }
  }

  enum class GpuProcessCapability : std::int32_t {
    PhotonPair = 0,
    Bremsstrahlung = 1,
    Compton = 2,
    Photoelectric = 3,
    Annihilation = 4,
    Ionization = 5,
    ElectronPair = 6,
    CpuOnlyFinalState = 7,
    GpuFinalStateNotImplemented = 8,
  };

  CORSIKA_GPU_CAPABILITY_HOST_DEVICE inline GpuProcessCapability
  gpuProcessCapability(std::int32_t pid, std::int32_t process_id) {
    if (pid == static_cast<std::int32_t>(EmPid::Photon) &&
        process_id == PhotonPairProcessId) {
      return GpuProcessCapability::PhotonPair;
    }
    if ((pid == static_cast<std::int32_t>(EmPid::Electron) ||
         pid == static_cast<std::int32_t>(EmPid::Positron)) &&
        process_id == BremsProcessId) {
      return GpuProcessCapability::Bremsstrahlung;
    }
    if (pid == static_cast<std::int32_t>(EmPid::Photon) &&
        process_id == ComptonProcessId) {
      return GpuProcessCapability::Compton;
    }
    if (pid == static_cast<std::int32_t>(EmPid::Photon) &&
        process_id == PhotoelectricProcessId) {
      return GpuProcessCapability::Photoelectric;
    }
    if (pid == static_cast<std::int32_t>(EmPid::Positron) &&
        process_id == AnnihilationProcessId) {
      return GpuProcessCapability::Annihilation;
    }
    if (isChargedLeptonPid(pid) &&
        process_id == IonizationProcessId) {
      return GpuProcessCapability::Ionization;
    }
    if (isMuonPid(pid) &&
        (process_id == BremsProcessId ||
         process_id == ElectronPairProcessId)) {
      // The device selects the exact process, target component and v. The
      // comparatively rare high-multiplicity muon final state is generated by
      // the existing specified-interaction PROPOSAL adapter on the CPU.
      return GpuProcessCapability::CpuOnlyFinalState;
    }
    if ((pid == static_cast<std::int32_t>(EmPid::Electron) ||
         pid == static_cast<std::int32_t>(EmPid::Positron)) &&
        process_id == ElectronPairProcessId) {
      return GpuProcessCapability::ElectronPair;
    }
    switch (process_id) {
    case PhotonuclearProcessId:
    case MuonPairProcessId:
    case HadronsProcessId:
    case WeakInteractionProcessId:
    case DecayProcessId:
    case PhotoproductionProcessId:
    case PhotonMuonPairProcessId:
      return GpuProcessCapability::CpuOnlyFinalState;
    default:
      return GpuProcessCapability::GpuFinalStateNotImplemented;
    }
  }

  CORSIKA_GPU_CAPABILITY_HOST_DEVICE inline ProposalFallbackReason
  processFallbackReason(GpuProcessCapability capability) {
    return capability == GpuProcessCapability::CpuOnlyFinalState
               ? ProposalFallbackReason::CpuOnlyProcess
               : ProposalFallbackReason::GpuProcessNotImplemented;
  }

  inline constexpr double NativeSelectionReplayEndpointWidth = 2.e-4;

  /**
   * Mark proposal-native selections whose final v must be replayed by the
   * scalar calculator using the same selection uniform.  CPU-only processes
   * already require a host final state, so replay avoids paying for a device
   * inverse that cannot improve that path.  For device final states, only a
   * narrow conditional-CDF endpoint band is replayed; this bounds the
   * amplification of the final host/device interpolation ULPs.
   */
  CORSIKA_GPU_CAPABILITY_HOST_DEVICE inline bool
  proposalNativeSelectionRequiresReplay(
      std::int32_t pid, std::int32_t process_id,
      double residual_quantile) {
    auto const capability = gpuProcessCapability(pid, process_id);
    if (capability == GpuProcessCapability::CpuOnlyFinalState) return true;
    // An endpoint replay is a numerical completion mechanism for processes
    // already covered by either a declared GPU final state or a declared
    // CPU-only final state.  It must never turn an unregistered process into
    // an implicit CPU fallback merely because its quantile lies near an
    // endpoint.
    if (capability ==
        GpuProcessCapability::GpuFinalStateNotImplemented) return false;
    return residual_quantile < NativeSelectionReplayEndpointWidth ||
           residual_quantile >
               1. - NativeSelectionReplayEndpointWidth;
  }

} // namespace corsika::gpu::em

#undef CORSIKA_GPU_CAPABILITY_HOST_DEVICE
